name: Build Go binaries
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - GOARCH: arm64
            name: arm64-v8a
          - GOARCH: mipsle
            GOMIPS: softfloat
            name: mips32le
          - GOARCH: mips
            GOMIPS: softfloat
            name: mips32
          - GOARCH: mips64
            name: mips64
          - GOARCH: mips64le
            name: mips64le
          - GOARCH: arm
            GOARM: 5
            name: arm32-v5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: ${{ matrix.GOARCH }}
          GOMIPS: ${{ matrix.GOMIPS }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -X main.version=$GITHUB_REF_NAME" -o xkeen-ui-${{ matrix.name }} main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xkeen-ui-${{ matrix.name }}
          path: xkeen-ui-${{ matrix.name }}
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update version in version.js
        run: |
          sed -i 's/const APP_VERSION = "dev"/const APP_VERSION = "'"$GITHUB_REF_NAME"'"/' version.js
          echo "Updated version to: $GITHUB_REF_NAME"

      - name: Pack static files
        run: |
          tar -czf xkeen-ui-static.tar.gz *.js *.css index.html favicon.png assets

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xkeen-ui-static
          path: xkeen-ui-static.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: [build, static]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -v "^${GITHUB_REF_NAME}$" | head -n1)
          if [ -z "$PREVIOUS_TAG" ]; then
            CHANGELOG=$(git log --reverse --pretty=format:"- %s (%h)" ${GITHUB_REF_NAME} -- script.js index.html style.css main.go bin/)
          else
            CHANGELOG=$(git log --reverse --pretty=format:"- %s (%h)" ${PREVIOUS_TAG}..${GITHUB_REF_NAME} -- script.js index.html style.css main.go bin/)
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          body: |
            ## Изменения:
            ${{ steps.changelog.outputs.changelog }}
